cloud:
    aws:
        credentials:
            access-key: ${accesskey}
            secret-key: ${secretkey}
        region:
            static: ${region}
        s3:
            bucket: ${bucket}
        stack:
            auto: false

spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB